[toolchain]
package_manager = "yarn"
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cipherpay = "C3qyHGtVXDTDqKR7ng1Q4ikYK2mKxyqtZLcWpgA1fKZV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = '~/.config/solana/id.json'

[test.validator]
bind_address = "127.0.0.1"
rpc_port = 18998


[scripts]
test = "cargo test -p cipherpay --test payout_protocol"
